# Generated by Django 3.0.5 on 2020-09-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddConstraint(
            model_name='authors',
            constraint=models.CheckConstraint(
                check=models.Q(models.Q(('first_name__isnull', False), ('second_name__isnull', False)),
                               ('company_name__isnull', False), _connector='OR'), name='authors_check_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='authors',
            constraint=models.UniqueConstraint(condition=models.Q(company_name__isnull=True),
                                               fields=('first_name', 'second_name'), name='authors_ind_1'),
        ),
        migrations.AddConstraint(
            model_name='authors',
            constraint=models.UniqueConstraint(condition=models.Q(company_name__isnull=False), fields=('company_name',),
                                               name='authors_ind_2'),
        ),
    ]
