# Generated by Django 3.1.1 on 2020-09-21 21:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("INSERT INTO books_authors (first_name,second_name,company_name) VALUES ('Corby','Bale','Daugherty, Volkman and Kutch'),('Orlando','Sharram','Grady and Sons'),('Boyd','Owthwaite','Zboncak, Lockman and Olson'),('Stearne','Fewkes','Jenkins-Ward'),('Carmine','McAuslan','Carter-Kuvalis'),('Vally','Whatsize','McCullough Inc'),('Uriel','Catcheside','Haley LLC'),('Gardiner','Scanes','Franecki, Hodkiewicz and Paucek')")]
