# Generated by Django 3.1.1 on 2020-09-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200922_1908'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='author',
            name='authors_check_not_empty',
        ),
        migrations.RemoveConstraint(
            model_name='author',
            name='authors_ind_1',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='second_name',
            new_name='last_name',
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('first_name__isnull', False), ('last_name__isnull', False)), ('company_name__isnull', False), _connector='OR'), name='authors_check_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='author',
            constraint=models.UniqueConstraint(condition=models.Q(company_name__isnull=True), fields=('first_name', 'last_name'), name='authors_ind_1'),
        ),
    ]
